language: node_js
node_js:
  - "9"

service:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER posttgres WITH PASSWORD 'mysecretpassword';" -U postgres
  - psql -U postgres -d postgres -a -f ./createUsers.sql

script:
  - cd current_nodejs/
  - yarn
  - yarn test --forceExit

notifications:
  email: false